### ISSUE TITLE
Not working with ILI9488

### ISSUE THREAD

**Issue by Trackhe** [atanisoft/esp_lcd_touch_xpt2046#3]
I try to use  Touch with ILI9488 3,5" 480x320 V1.0 XPT2046
But i don't get any error or Data.

I had it working 2021 with an older version of driver.
https://github.com/lvgl/lvgl_esp32_drivers

I have disconnected the SDO from the touch, according too https://github.com/lvgl/lvgl_esp32_drivers/issues/91
But even with that no data from the touch.

Do you have any idea what can be wrong? Its the same touch code that i use with an ili9341 where the xtp2046 is working with lvgl.

I use the esp error check function and so on but nothing, not even an error. 

I call from the lvgl timer handler loop 
`ESP_ERROR_CHECK(esp_lcd_touch_read_data(tp));`

but 

```c
void touch_driver_read(lv_indev_drv_t *drv, lv_indev_data_t *data)
{
    ESP_LOGI(TAG, "Read Touch Data");
    uint16_t x[1];
    uint16_t y[1];
    uint16_t strength[1];
    uint8_t count = 0;

    // Update touch point data.
    ESP_ERROR_CHECK(esp_lcd_touch_read_data(tp));

    data->state = LV_INDEV_STATE_REL;

    if (esp_lcd_touch_get_coordinates(tp, x, y, strength, &count, 1))
    {
        ESP_LOGI(TAG, "Touch Data %hu, %hu, %hu", *x, *y, *strength);
        data->point.x = x[0];
        data->point.y = y[0];
        data->state = LV_INDEV_STATE_PR;
    }

    data->continue_reading = false;
}
```

seems never get called.

**Comment by atanisoft** [comment]
If you can please provide some example code which shows the issue not working. Based on what you have reported it would seem you don't have the touch indev registered with lvgl, you should also not be calling `esp_lcd_touch_read_data` directly as that normally will be called by lvgl directly when the indev is registered.

**Comment by Trackhe** [comment]
I had the same thought and then checked. I really forgot that code but i have added this back but no change.
I use:
```c
  //Touch with LVGL
  lv_indev_drv_t indev_drv;
  lv_indev_drv_init( &indev_drv );
  indev_drv.type = LV_INDEV_TYPE_POINTER;
  indev_drv.read_cb = touch_driver_read;
  lv_indev_drv_register( &indev_drv );
```

**Comment by atanisoft** [comment]
Interesting, that should be working unless there is a setup problem with the IO pin connections.

**Comment by Trackhe** [comment]
![IMG_8085](https://github.com/atanisoft/esp_lcd_touch_xpt2046/assets/1494328/b1b56d92-886c-484f-adaa-07b3c7f29b0e)
![IMG_8087](https://github.com/atanisoft/esp_lcd_touch_xpt2046/assets/1494328/8afbf33c-5acd-4e97-980d-c1be93b0cdb1)
Its a bit janky but that should work or not? The cs pin from the touch is connected on pin 4 which i also used with the other display.

**Comment by atanisoft** [comment]
It's certainly not pretty but I think it should work. You can ignore T_IRQ as the code doesn't support using it (yet) since it is not implemented in esp_lcd_touch (yet).

**Comment by Trackhe** [comment]
Actually the only T pins that are connected is CS to IO4, T_CLK to SCK Display, T_DIN, SDI Display

**Comment by Trackhe** [comment]
I don't know how to continue to debug it, so i make a bit later that day a new project only with the display, maybe that would help to find the problem.

**Comment by atanisoft** [comment]
If you can provide some code that reproduces the issue I can test with my hardware on breadboards etc and see if I can reproduce it.

From testing this was working correctly, I did not solder to the TFT PCB pins but instead used dupont jumpers on the breadboard while working on a custom PCB for a project.

**Comment by Trackhe** [comment]
So after a bit of work ^^

https://github.com/Trackhe/display_ili9488_ili9341

**Comment by Trackhe** [comment]
If i combine
https://github.com/atanisoft/esp_lcd_ili9488/tree/main/examples/lvgl
and
https://github.com/atanisoft/esp_lcd_touch_xpt2046
i get another example: https://github.com/Trackhe/lvgl

with the result of:
```
I (347629) main: Touch Data 0, 0, 4096
I (347669) main: Touch Data 0, 0, 4096
I (347709) main: Touch Data 0, 0, 4096
I (347739) main: Touch Data 0, 0, 4096
I (347779) main: Touch Data 0, 0, 4096
I (347819) main: Touch Data 0, 0, 4096
I (347859) main: Touch Data 0, 0, 409...
```

**Comment by atanisoft** [comment]
Thanks for the examples, I'll be reviewing them as soon as I can (a bit busy right now to dig into it). I'll also look at including one of these into this repository as a test case (likely one supporting both ili9341 and ili9488).

From a very quick look at both examples you've provided they are nearly identical to the test case I was using during initial development except I used esp_lvgl_port rather than directly manage LVGL tick/updates/etc.

**Comment by Trackhe** [comment]
Yes i want to build my example for supporting more then one. I had a ili9341 which uses also the same touch controller and there is the touch lib from you working but with the oder dp not

**Comment by Trackhe** [comment]
> Thanks for the examples, I'll be reviewing them as soon as I can (a bit busy right now to dig into it). I'll also look at including one of these into this repository as a test case (likely one supporting both ili9341 and ili9488).
> 
> 
> 
> From a very quick look at both examples you've provided they are nearly identical to the test case I was using during initial development except I used esp_lvgl_port rather than directly manage LVGL tick/updates/etc.

Any update?

**Comment by atanisoft** [comment]
Sorry I've been a bit busy to be able to test and reproduce this.

**Comment by Trackhe** [comment]
No problem but i had to ask, maybe you have any idea how i can find the solution out by myself. but maybe i should look into the datasheet and dig around

**Comment by atanisoft** [comment]
I'm pretty sure it is how the SPI bus is being initialized. I've tested (as well as others) on the ESP32-S3 without issues. I will need to dig out an ESP32 and review the esp_lcd / esp_lcd_touch SPI mapping to figure out for sure though.

**Comment by Trackhe** [comment]
The problem seems that the displays dont use the same chips. I have ordered two more, and they come all now with an diffrent chip.

![image](https://github.com/atanisoft/esp_lcd_touch_xpt2046/assets/1494328/f0855625-19cc-4d24-b1d6-eb02635af10a)![image](https://github.com/atanisoft/esp_lcd_touch_xpt2046/assets/1494328/8023a458-31cd-4326-a3b1-31848a75bce2)

**Comment by Trackhe** [comment]
Jea, if i search for the HR2046 it is saled as XTP2046 too and i diddn’t find any new datasheet for the HR2046 but on github exist https://github.com/search?q=HR2046&type=repositories repositorys that are only as a hint something worth i guess.

**Comment by atanisoft** [comment]
Thanks for the library link, it does in fact look like it uses a different register setup. Try changing https://github.com/atanisoft/esp_lcd_touch_xpt2046/blob/main/esp_lcd_touch_xpt2046.c#L27C14-L28 from 0x90, 0xDO to 0x91, 0xD1.

**Comment by Trackhe** [comment]
Same problem:
```

I (55773) SHP HK: adc: 281329489.488860; 0
I (55783) SHP HK: Touch Data 320, 240, 4096
I (55813) SHP HK: Touch Data 320, 240, 4096
I (55843) SHP HK: Touch Data 320, 240, 4096
I (55873) SHP HK: Touch Data 320, 240, 4096
I (55903) SHP HK: Touch Data 320, 240, 4096
I (55933) SHP HK: Touch Data 320, 240, 4096
I (55973) SHP HK: Touch Data 320, 240, 4096
I (55973) SHP HK: adc: 281329489.488860; 0
I (56003) SHP HK: Touch Data 320, 240, 4096
I (56033) SHP HK: Touch Data 320, 240, 4096
I (56063) SHP HK: Touch Data 320, 240, 4096
I (56093) SHP HK: Touch Data 320, 240, 4096
I (56123) SHP HK: Touch Data 320, 240, 4096
I (56153) SHP HK: Touch Data 320, 240, 4096
I (56173) SHP HK: adc: 281329489.488860; 0
I (56183) SHP HK: Touch Data 320, 240, 4096
I (56223) SHP HK: Touch Data 320, 240, 4096
I (56253) SHP HK: Touch Data 320, 240, 4096
I (56283) SHP HK: Touch Data 320, 240, 4096
I (56313) SHP HK: Touch Data 320, 240, 4096
I (56343) SHP HK: Touch Data 320, 240, 4096
```

**Comment by Trackhe** [comment]
> ![IMG_8085](https://user-images.githubusercontent.com/1494328/245157558-b1b56d92-886c-484f-adaa-07b3c7f29b0e.jpg) ![IMG_8087](https://user-images.githubusercontent.com/1494328/245157584-8afbf33c-5acd-4e97-980d-c1be93b0cdb1.jpg) Its a bit janky but that should work or not? The cs pin from the touch is connected on pin 4 which i also used with the other display.
> 
> I also double check it.

@atanisoft seems working with both adresses. I m only stupid ^^'

in this post i showed up the connection and explained it but i don't thought how the data would get back into the ESP, i only thought about the disconnection of the SDA from T_DOUT but i didn't connected the T_DOUT instead of the SDO then. That was very my foult. Thank you so mouch for yout time and patient.

**Comment by atanisoft** [comment]
Thanks for confirming, I'll take your examples you linked above and create a few examples in this repository in the near future.
