### ISSUE TITLE
Variable wrong

### ISSUE THREAD

**Issue by ZoranIT** [atanisoft/esp_lcd_touch_xpt2046#4]
https://github.com/atanisoft/esp_lcd_touch_xpt2046/blob/ede6c4f05f96991e48990c7da426eef7c995001b/esp_lcd_touch_xpt2046.c#L76C68-L76C68

` 

    if (config->int_gpio_num != GPIO_NUM_NC)
    {
        ESP_GOTO_ON_FALSE(GPIO_IS_VALID_GPIO(config->int_gpio_num),
               ESP_ERR_INVALID_ARG, err, TAG, "Invalid GPIO Interrupt Pin");
`
This should be int_gpio_num instead of rst_gpio_num, or?

**Comment by atanisoft** [comment]
Thanks for catching this, you are 100% correct in that it should be "int_gpio_num" and not "rst_gpio_num". I'll fix this up shortly and also be adding the rest of the support for interrupt callbacks now that esp_lcd_touch supports it (v1.0.4 and above for esp_lcd_touch)
